# Generated by Django 2.2.1 on 2019-09-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0003_functions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codCliente', models.CharField(max_length=150, verbose_name='cod')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('cpf', models.CharField(max_length=50, verbose_name='cpf')),
                ('cidadeCliente', models.CharField(max_length=50, verbose_name='cidade')),
            ],
        ),
    ]
