# Generated by Django 2.2.1 on 2019-09-13 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0004_cliente'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Clientes',
        ),
    ]
