# Generated by Django 2.2.1 on 2019-09-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0005_auto_20190913_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cidadeCliente',
            field=models.CharField(max_length=50, verbose_name='cidadeCliente'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='codCliente',
            field=models.CharField(max_length=150, verbose_name='codCliente'),
        ),
    ]
