# Generated by Django 2.2.1 on 2019-09-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0006_auto_20190913_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='id',
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cidadeCliente',
            field=models.CharField(max_length=50, verbose_name='cidade'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='codCliente',
            field=models.CharField(max_length=150, primary_key=True, serialize=False, verbose_name='cod'),
        ),
    ]
